const std = @import("std");

pub fn build(b: *std.Build) !void {
    const optimize = b.standardOptimizeOption(.{});
    const target = b.standardTargetOptions(.{});

    const config: Config = .fromOptions(b);

    const sx1302_hal = b.dependency("sx1302_hal", .{
        .optimize = optimize,
        .target = target,
    });

    const loragw_mod = b.addModule("loragw", .{
        .root_source_file = b.path("loragw.zig"),
        .optimize = optimize,
        .target = target,
        .link_libc = true,
        .sanitize_c = config.sanitize_c,
    });

    const config_file = b.addWriteFile("config.h", config.header(b));

    loragw_mod.addIncludePath(sx1302_hal.path("libloragw/inc"));
    loragw_mod.addIncludePath(sx1302_hal.path("libtools/inc"));
    loragw_mod.addIncludePath(config_file.getDirectory());

    loragw_mod.addCSourceFiles(.{
        .root = sx1302_hal.path("libloragw/src"),
        .files = &.{
            "loragw_ad5338r.c",
            "loragw_aux.c",
            "loragw_cal.c",
            "loragw_com.c",
            "loragw_debug.c",
            "loragw_gps.c",
            "loragw_hal.c",
            "loragw_i2c.c",
            "loragw_lbt.c",
            "loragw_mcu.c",
            "loragw_reg.c",
            "loragw_spi.c",
            "loragw_stts751.c",
            "loragw_sx1250.c",
            "loragw_sx125x.c",
            "loragw_sx1261.c",
            "loragw_sx1302.c",
            "loragw_sx1302_rx.c",
            "loragw_sx1302_timestamp.c",
            "loragw_usb.c",
            "sx1250_com.c",
            "sx1250_spi.c",
            "sx1250_usb.c",
            "sx125x_com.c",
            "sx125x_spi.c",
            "sx1261_com.c",
            "sx1261_spi.c",
            "sx1261_usb.c",
        },
        .flags = &.{},
    });

    loragw_mod.addCSourceFiles(.{
        .root = sx1302_hal.path("libtools/src"),
        .files = &.{
            "tinymt32.c",
            "base64.c",
            "parson.c",
        },
        .flags = &.{},
    });

    const loragw_lib = b.addLibrary(.{
        .root_module = loragw_mod,
        .linkage = config.linkage,
        .name = "loragw",
    });

    b.installArtifact(loragw_lib);
}

pub const Config = struct {
    sanitize_c: std.zig.SanitizeC = .off,
    linkage: std.builtin.LinkMode = .static,
    debug_hal: bool = false,
    debug_reg: bool = false,
    debug_spi: bool = false,
    debug_aux: bool = false,
    debug_gps: bool = false,
    debug_lbt: bool = false,
    debug_i2c: bool = false,
    debug_com: bool = false,
    debug_gpio: bool = false,

    pub const template: [:0]const u8 = (
        \\/* Generated by zloragw/build.zig */
        \\#ifndef _LORAGW_CONFIG_H
        \\#define _LORAGW_CONFIG_H
        \\
        \\#define LIBLORAGW_VERSION "2.1.0"
        \\
        \\#define DEBUG_HAL  {d}
        \\#define DEBUG_REG  {d}
        \\#define DEBUG_SPI  {d}
        \\#define DEBUG_AUX  {d}
        \\#define DEBUG_GPS  {d}
        \\#define DEBUG_LBT  {d}
        \\#define DEBUG_I2C  {d}
        \\#define DEBUG_COM {d}
        \\#define DEBUG_GPIO {d}
        \\
        \\#endif /* _LORAGW_CONFIG_H */
    );

    pub fn header(config: Config, b: *std.Build) [:0]const u8 {
        return std.fmt.allocPrintSentinel(b.allocator, "{f}", .{config}, 0) catch unreachable;
    }

    pub fn fromOptions(b: *std.Build) Config {
        var config: Config = .{};

        inline for (std.meta.fields(Config)) |field| {
            if (b.option(field.type, field.name, "enable " ++ field.name)) |opt| {
                @field(config, field.name) = opt;
            }
        }

        return config;
    }

    pub fn format(config: Config, writer: *std.Io.Writer) !void {
        try writer.print(template, .{
            @intFromBool(config.debug_hal),
            @intFromBool(config.debug_reg),
            @intFromBool(config.debug_spi),
            @intFromBool(config.debug_aux),
            @intFromBool(config.debug_gps),
            @intFromBool(config.debug_lbt),
            @intFromBool(config.debug_i2c),
            @intFromBool(config.debug_com),
            @intFromBool(config.debug_gpio),
        });
    }
};
